model:
  name: "prithvi_mae"
  img_size: 96
  num_channels: 10
  num_timestamps: 2

dataset:
  batch_size: 1024
  num_workers: 4
  train:
    name: "ibge"
    data_dir: "/storage/datasets/gabriel.lima/IBGE"
  test:
    name: "ibge"
    data_dir: "/storage/datasets/gabriel.lima/IBGE"

solver:
  name: "adam"
  learning_rate: 1e-4
  weight_decay:
  warmup_epochs: 40
  max_epochs: 400
  dev_run: False # Set to True for a quick test run

checkpoint:
  save_dir: "/home/gabriel.lima/pretrain_ibge"
  run_name: "ibge_first_run"
  ckpt_path:
  save_checkpoint: True